Add a sample Tensorflow funtion
knative-sandbox/func-tastic pull request #17
Opened 2022-11-16 02:05 UTC by chzhyang

# Changes

This sample HTTP function is used for real-time inference(image recognition) with TensorFlow on a pretrained model(ResNet50).

- The function(`func.py`) is based on class `ImageRecognitionService`(`image_recognition_service.py`), and provide GET and POST interface for inference.
- Class `ImageRecognitionService` defines several functions for data preprocessing, running inference and inference result parsing using optimized TensorFlow.

2022-11-22 22:25 UTC, matejvasek commented on tensorflow/image-recognition/func.yaml
> +specVersion: 0.34.0
The `func.yaml` config shouldn't be part of "template" AFAIK.
If any values need default value `manifest.yaml`  should be used.

2022-11-22 22:39 UTC, matejvasek commented on tensorflow/image-recognition/func.py
> +from http.client import BAD_REQUEST
Is this different from `werkzeug.exceptions.BadRequest` which is also imported?

2022-11-22 22:46 UTC, matejvasek commented on tensorflow/image-recognition/requirements.txt
> +intel-tensorflow==2.9.1
I know absolutely nothing about tensorflow.
Is there difference between `intel-tensorflow` and `tensorflow` packages?
Would `intel-tensorflow` work on ARM machine?

2022-11-24 08:04 UTC, chzhyang commented on tensorflow/image-recognition/func.yaml
> +specVersion: 0.34.0
I will update it to default value.

2022-11-24 08:06 UTC, chzhyang commented on tensorflow/image-recognition/func.py
> +from http.client import BAD_REQUEST
Thanks, they are the same, I will delete one :)

2022-11-24 08:17 UTC, chzhyang commented on tensorflow/image-recognition/requirements.txt
> +intel-tensorflow==2.9.1
The [intel-tensorflow](https://pypi.org/project/intel-tensorflow/2.9.1/) was optimized on [tensorflow](https://pypi.org/project/tensorflow/2.9.1/),  it supports all x86 platforms and the performance is better, but it does not support ARM.

2022-11-24 12:40 UTC, matejvasek commented on tensorflow/image-recognition/func.yaml
> +specVersion: 0.34.0
I meant that this file shouldn't  be part of this PR at all.

2022-11-24 12:44 UTC, matejvasek commented
I also think this should be under the python dir, right?

2022-11-24 13:40 UTC, matejvasek commented on tensorflow/image-recognition/func.yaml
> +specVersion: 0.34.0
This file should be deleted.

2022-11-24 13:48 UTC, matejvasek commented
@chzhyang  Not related to this PR:
I don't know ML/Tensorflow. I wonder what is the character of the model binary with regard to change.
Does update to the model usually changes most of the content, or does it only change partially?
I am asking because I am working on `rsync` source upload for on-cluster-build, which is efficient for partial updates.

2022-11-25 06:27 UTC, chzhyang commented on tensorflow/image-recognition/func.yaml
> +specVersion: 0.34.0
Sorry, I will remove this file :)

2022-11-25 06:28 UTC, chzhyang commented
> I also think this should be under the python dir, right?

OK, it will be moved to python dir

2022-11-25 08:35 UTC, chzhyang commented
> @chzhyang Not related to this PR: I don't know ML/Tensorflow. I wonder what is the character of the model binary with regard to change. Does update to the model usually changes most of the content, or does it only change partially? I am asking because I am working on `rsync` source upload for on-cluster-build, which is efficient for partial updates.

Roughly speaking, the degree of model change varies [case by case](https://machinelearningmastery.com/update-neural-network-models-with-more-data/), related to changes of model architecture, data feature...but minmizing model change of model updating is a consistent pursuit(reduce cost) in deep learning. 
A model has many layers. Each layer represents different features and it can be imagined as a matrix composed of weights.
Most `fine-tuning` on base model just need to change serveral layers to update the representations of higher-order/lower-order feature, which means `partial` updates.  

fine-tuning:
- http://d2l.ai/chapter_computer-vision/fine-tuning.html
- https://www.tensorflow.org/tutorials/images/transfer_learning

Hope this can help you :)

2022-11-28 18:14 UTC, lance reviewed
@chzhyang thank you for this contribution! In order to work with `func create` the templates should be one directory below the target language/runtime. E.g. `python/tensorflow-image-recognition`. Unfortunately, the CLI cannot handle sub-directories such as `python/tensorflow/image-recognition` at the moment. Can you please move the template to a single directory under `python`?

2022-11-29 03:08 UTC, chzhyang commented on python/tensorflow/image-recognition/README.md
> +## Create funtion
Thanks, I will fix it and move the directory :)

2022-11-29 03:09 UTC, chzhyang commented on python/tensorflow/image-recognition/README.md
> +$ cd tensorflow/image_recognition
Thank you, docs will be updated

2022-11-29 03:10 UTC, chzhyang commented on python/tensorflow/image-recognition/README.md
> +    └── requirements.txt
Thank you, addressed.

2022-11-29 03:11 UTC, chzhyang commented on python/tensorflow/image-recognition/README.md
> +$ func build -i docker.io/chzhyang/tensorflow-image-recognition:latest
addressed.

2022-11-29 21:01 UTC, lance requested changes
EDIT: Please disregard this. I realize that your function is not a cloudevent function and therefore does not need to have this annotation. However, something is still not working correctly. I'll need to dig further into this.


@chzhyang this is looking great! I tried it out locally, and realized that you'll need to have a `manifest.yaml` file in the root of `python/tensorflow-image-recognition` with the following contents in order for `func invoke` to work as expected.

```
invocation:
  format: cloudevent
```
Adding this `manifest.yaml` will override the defaults that are applied in a project's `func.yaml` when it is initially created. The default, if unspecified, is `http`.

2022-11-30 01:12 UTC, lance approved these changes
My issues seemed to be local. /lgtm

2022-11-30 01:12 UTC, lance commented
/lgtm

2022-11-30 01:13 UTC, lance commented
/approve

2022-11-30 01:13 UTC, merged

2022-11-30 13:19 UTC, matejvasek commented
> > @chzhyang Not related to this PR: I don't know ML/Tensorflow. I wonder what is the character of the model binary with regard to change. Does update to the model usually changes most of the content, or does it only change partially? I am asking because I am working on `rsync` source upload for on-cluster-build, which is efficient for partial updates.
> 
> Roughly speaking, the degree of model change varies [case by case](https://machinelearningmastery.com/update-neural-network-models-with-more-data/), related to changes of model architecture, data feature...but minmizing model change of model updating is a consistent pursuit(reduce cost) in deep learning. A model has many layers. Each layer represents different features and it can be imagined as a matrix composed of weights. Most `fine-tuning` on base model just need to change serveral layers to update the representations of higher-order/lower-order feature, which means `partial` updates.
> 
> fine-tuning:
> 
> * http://d2l.ai/chapter_computer-vision/fine-tuning.html
> * https://www.tensorflow.org/tutorials/images/transfer_learning
> 
> Hope this can help you :)

@chzhyang could you please point me to some git repos where model changed?

2022-12-01 02:16 UTC, chzhyang commented
> 



> > > @chzhyang Not related to this PR: I don't know ML/Tensorflow. I wonder what is the character of the model binary with regard to change. Does update to the model usually changes most of the content, or does it only change partially? I am asking because I am working on `rsync` source upload for on-cluster-build, which is efficient for partial updates.
> > 
> > 
> > Roughly speaking, the degree of model change varies [case by case](https://machinelearningmastery.com/update-neural-network-models-with-more-data/), related to changes of model architecture, data feature...but minmizing model change of model updating is a consistent pursuit(reduce cost) in deep learning. A model has many layers. Each layer represents different features and it can be imagined as a matrix composed of weights. Most `fine-tuning` on base model just need to change serveral layers to update the representations of higher-order/lower-order feature, which means `partial` updates.
> > fine-tuning:
> > 
> > * http://d2l.ai/chapter_computer-vision/fine-tuning.html
> > * https://www.tensorflow.org/tutorials/images/transfer_learning
> > 
> > Hope this can help you :)
> 
> @chzhyang could you please point me to some git repos where model changed?

TensorFlow gived a sample for model fine-tuning: 
- https://www.tensorflow.org/tutorials/images/transfer_learning
- https://github.com/tensorflow/docs/blob/master/site/en/tutorials/images/transfer_learning.ipynb